import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import classNames from 'classnames';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="w-full h-full"
    >
      <body
        className={classNames([
          inter.className,
          'w-full h-full p-4 flex flex-col',
        ])}
      >
        {children}
      </body>
    </html>
  );
}
